config/routes.rb
Rails.application.routes.draw do

  get 'sessionsgem/install'

  get 'sessionsgem/bcrypt'

  
  root "welcome#index"
  
  match "test_templates/upload" => "test_templates#upload", via: [:get, :post]
  match "test_templates/save" => "test_templates#save", via: [:get, :post]
  match "students/get_test" => "students#get_test", via: [:get, :post]
  match "students/choose_student" => "students#choose_student", via: [:get, :post]
  match "students/show_record" => "students#show_record", via: [:get, :post]
  get "students/authorize" => "students#authorize"
  post "students/authorize_test" => "students#authorize_test"
  match "students/authorize_reentry" => "students#authorize_reentry", via: [:get, :post]
  post "students/authorize_reentry_test" => "students#authorize_reentry_test"
  get "test_templates/" => "test_templates#index"
  get "test_templates/show_test" => "test_templates#show_test"
  get "test_templates/destroy" => "test_templates#destroy"
  get "users/add" => "users#add"
  get "test_taker/show_test" => "test_taker#show_test"
  get "test_results/show_test" => "test_results#show_test"
  match "test_results/score" => "test_results#score", via: [:get, :post]
  match "courses/remove_student" => "courses#remove_student", via: [:get, :post]
  
  delete "users/:id" => "users#destroy"
  delete "users" => "users#destroy"
  
  resources :users, :instructors, :courses, :answer_records, :test_results, :test_templates, :students
  
  match "/login" => "admin#login", via: [:get, :post]
  match "/admin" => "admin#login", via: [:get, :post]
  match "answer/analyze_test" => "answer#analyze_test", via: [:get, :post]
  match "answer/analyze_problem" => "answer#analyze_problem", via: [:get, :post]
  match "admin/choose_student" => "students#choose_student", via: [:get, :post]
  get "admin/index" => "admin#index"
  get "admin/try-test" => "admin#try_test"
  match "admin/try_test" => "admin#try_test", via: [:get, :post]
  get "admin/authorize" => "admin#authorize"
  match "admin/authorize_class" => "admin#authorize_class", via: [:get, :post]
  match "admin/authorize_class_test" => "admin#authorize_class_test", via: [:get, :post]
  get "admin/authorize_class_test" => "admin#authorize_class_test"
  match "admin/add_student_to_course" => "admin#add_student_to_course", via: [:get, :post]
  get "admin/get_student_record" => "admin#get_student_record"
  get "admin/authorize_reentry" => "admin#authorize_reentry"
  get "admin/logout" => "admin#logout"
  match "admin/login" => "admin#login", via: [:get, :post]
  get "admin/list_users" => "admin#list_users"
  get "admin/destroy_user" => "admin#destroy_user"
  get "admin/new_user" => "admin#new_user"
  get "admin/edit_user" => "admin#edit_user"
  get "admin/add_user" => "admin#add_user"
  get "admin/add_course" => "admin#add_course"
  match "admin/add_test_to_course" => "admin#add_test_to_course", via: [:get, :post]
  get "admin/show_test_try" => "admin#show_test_try"
  get "admin/test_results" => "admin#test_results"
  match "admin/show_test_results" => "admin#show_test_results", via: :post
  match "admin/score_try" => "admin#score_try", via: [:get, :post]
  match "admin/update_answers" => "admin#update_answers", via: [:get, :post]
  match "admin/add_students" => "admin#add_students", via: [:get, :post]
  match "admin/show_class" => "admin#show_class", via: [:get, :post]
  match "test_taker/update_answers" => "test_taker#update_answers", via: [:get, :post]
  get "answer/analyze_answers" => "answer#analyze_answers"
  get "instructor/create" => "instructor#create"

end

app/models/test_result.rb
# == Schema Information
# Schema version: 11
#
# Table name: test_results
#
#  id               :integer(11)   not null, primary key
#  answers          :string(255)   
#  test_items       :text          
#  score            :float         
#  status           :string(255)   
#  start_time       :datetime      
#  student_id       :integer(11)   
#  course_id        :integer(11)   
#  test_template_id :integer(11)   
#

class TestResult < ActiveRecord::Base

  belongs_to  :student
  belongs_to  :course
  belongs_to  :test_template
  has_many    :answer_records

  validates_presence_of   :status, :start_time, :student_id, :course_id, :test_template_id

end

app/controllers/test_results_controller.rb
class TestResultsController < ApplicationController
  before_action :set_test_result, only: [:show, :edit, :update, :destroy]

  layout "admin"

  # GET /test_results
  def index
    @test_results = TestResult.all
  end

  # GET /test_results/1
  def show
    @test_result = TestResult.find(params[:id])
  end

  # GET /test_results/new
  def new
    @test_result = TestResult.new
  end

  # GET /test_results/1/edit
  def edit
    @test_result = TestResult.find(params[:id])
  end

  # POST /test_results
  def create
    @test_result = TestResult.new(test_result_params)

       if @test_result.save
        redirect_to @test_result, notice: 'Test result was successfully created.' 
      else
        render :new 
      end
  end

  # PATCH/PUT /test_results/1
  def update
      if @test_result.update(test_result_params)
        redirect_to @test_result, notice: 'Test result was successfully updated.' 
      else
        render :edit 
      end
  end

  # DELETE /test_results/1
  def destroy
    @test_result.destroy
    redirect_to test_results_url, notice: 'Test result was successfully destroyed.' 
  end

  def get_test
    if request.post?
      current_time = Time.now.strftime("%Y-%m-%d %H:%M:%S")
      @student = Student.find_by_student_number(params[:student_number])
      if @student
        test_result = TestResult.find(:all, :conditions => ["status = ? and student_id = ? and start_time >= ?",'authorized',@student.id,current_time])
        if test_result.length == 0
          flash[:notice] = "No tests are currently authorized for student id #{params[:student_number]}."
        else
          redirect_to(:controller => 'test_taker', :action => 'show_test', :student => params[:student_number], :test_results => test_result[0].id)
        end
      else
        flash[:notice] = "No student found with student id #{params[:student_number]}."
      end
    end
  end

  def score
    require 'open-uri'
    if session[:test_results_id]
      @test_results = TestResult.find(session[:test_results_id])
    else
      @test_results = TestResult.find(params[:test_results_id])
    end
    @student = Student.find(@test_results.student)
    if @test_results.status == 'finished'
      flash[:notice] = "This test has already been scored."
    end
    @test_results.status = 'finished'
    answers = @test_results.answers.split("<*>")
    @problem_list = @test_results.test_items.split("<*>")
    n = @problem_list.length
    choices = []
    l = "A"
    26.times do 
    	 choices << l
       l = l.succ
    end
    i = 0
    score = 0
    @user_answers = []
    @key = []
    @missed_questions = []
		answertonumber = ["A" => 1, "B" => 2, "C" => 3, "D" => 4, "E" => 5];
		numbertoanswer = ["","A","B","C","D","E"];
    AnswerRecord.destroy_all("test_result_id = #{@test_results.id}")
    answer_records = []
    answer_records_valid = true
    @problem_list.each do |p|
      code = p[p.length-1,1]
      if code == "m"
        i += 1
        folder = p.split("/")[1]
        problem = p.split("/")[2]
        if folder == "PEmultchoiceimages"
          problem += ".pedr"
        elsif folder == "5multchoiceimages"
          problem += ".5jpg"
        else
          problem += ".jpg"
        end
        keystring = p.split("/")[3].split(".")[0].gsub(",","")
        number_choices = keystring.length
        key_answer = choices[keystring.index("1")]
        @key << key_answer
        temp_answer = params[i.to_s]
        if temp_answer.nil?
          temp_answer = answers[i-1].split(" ")
          temp_answer = temp_answer[1]
        else
          answers[i-1] = i.to_s + " " + temp_answer
        end
        user_answer = temp_answer.to_s
        @user_answers << user_answer
        if user_answer == key_answer
          score += 1
        else
          @missed_questions << i.to_s + "<*>" + user_answer + "<*>" + key_answer +"<*>" + p
        end
        j = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".index(user_answer)
        if j.nil?
          decoded_answer = ""
        else
          decoded_answer = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"[keystring[j,1].to_i-1,1]
        end
      elsif code == "f"
        i += 1
        temp_answer = answers[i-1].split(" ")
        temp_answer.delete_at(0)
        user_answer = temp_answer.to_s
        parray = p.split("?")[1].split("&")
        encoded_problem = parray[0].split("=")[1]
        problem = URI.decode(encoded_problem)
        keylines = []
        open("http://math.lanecc.edu/getproblemanswers?problem=#{encoded_problem}&seed=#{parray[3].split("=")[1]}&useranswer=#{user_answer}") do |f|
          keylines << f.readlines
        end
        keystring = keylines[0].to_s
        keyarray = keystring.split(";<br>")
        key_answer = keyarray[0]
        @key << key_answer
        @user_answers << user_answer
        decoded_answer = ""
        j = 0
        decoded_answer = "N"
        keylines.to_s.split("<br>\n").each do |k|
          if k.to_s.split(";<br>")[1].to_i == 1
            decoded_answer = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"[j,1]
          end
          j += 1
        end
        if keyarray[1].to_i == 1
          score += 1
        else
          @missed_questions << i.to_s + "<*>" + user_answer + "<*>" + key_answer +"<*>" + p          
        end
        @keylines = keylines
      else
          next
      end
      answer_record = AnswerRecord.new(:problem => problem, 
                                      :decoded_answer => decoded_answer, 
                                      :start_time => @test_results.start_time,
                                      :test_result => @test_results,
                                      :course => @test_results.course,
                                      :test_template => @test_results.test_template )
      answer_records << answer_record
      if not answer_record.valid?
        answer_records_valid = false
      end
    end
    if answer_records_valid
      answer_records.each {|a| a.save}
    else
      flash[:notice] = "Unable to save answer records for data analysis as not all were valid."
    end
    @test_results.answers = answers.join("<*>")
    @score = score/1.0/i
    @test_results.score = score/1.0/i
    @test_results.save
  end

  def show_test
    @test_results = TestResult.find(params[:test_results_id])
    @time = @test_results.start_time
    @student = Student.find(@test_results.student_id)
    @test = TestTemplate.find(@test_results.test_template)
    @test_list = @test_results.test_items.split("<*>")
    @n = @test_list[2].to_i
    @answers = Answers.new
    @answers.items = @test_results.answers.split("<*>")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_result
      @test_result = TestResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_result_params
      params.require(:test_result).permit(:answers, :test_items, :score,:status, :start_time)
    end
end

app/helpers/test_results_helper.rb
module TestResultsHelper
end

app/views/test_results/_answer_item.html.erb
<% if answer_item == @current_answer %>
	<tr id="current_answer">
<% else %>
	<tr>
<% end %>
<td><a href="#<%= answer_item.split(" ")[0] %>"><%= answer_item %></a></td>
</tr>

app/views/test_results/_answers.html.erb
<div class="answer-title">Answers</div>
<table>
<%= render(:partial => "answer_item", :collection => answers.items) %>
</table>

app/views/test_results/_choice.html.erb
<TR>
	<TD WIDTH=50 height=25 ALIGN=LEFT>
		<input name="<%= i %>" type=radio value="<%= choice %>" onClick="addAnswer(<%= i %>,'<%= choice %>')"><%= choice %>.</TD>
</TR>

app/views/test_results/_choice_selected.html.erb
<TR>
	<TD WIDTH=50 height=25 ALIGN=LEFT>
		<input name="<%= i %>" type=radio value="<%= choice %>" onClick="addAnswer(<%= i %>,'<%= choice %>')" checked ><%= choice %>.</TD>
</TR>

app/views/test_results/_form.html.erb
<%= form_for(@test_result) do |f| %>
  <% if @test_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_result.errors.count, "error") %> prohibited this test_result from being saved:</h2>

      <ul>
      <% @test_result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p><label for="test_result_name">Answers</label><br/>
<%= text_field 'test_result', 'answers'  %></p>

<p><label for="test_result_result">Test items</label><br/>
<%= text_area 'test_result', 'test_items'  %></p>

<p><label for="test_result_description">Score</label><br/>
<%= text_field 'test_result', 'score'  %></p>

<p><label for="test_result_result">Status</label><br/>
<%= text_field 'test_result', 'status'  %></p>

<p><label for="test_result_Start time">Score</label><br/>
<%= text_field 'test_result', 'start_time'  %></p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_results/edit.html.erb
<h1>Editing test_result</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_result %> |
<%= link_to 'Back', test_results_path %>

app/views/test_results/index.html.erb
<h1>Listing test_results</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
	  <tr>
	  <% for column in TestResult.content_columns %>
	    <th><%= column.human_name %></th>
	  <% end %>
	  </tr>
    <% @test_results.each do |test_result| %>
      <tr>
		  <% for column in TestResult.content_columns %>
		    <td><%=h test_result.send(column.name) %></td>
		  <% end %>
        <td><%= link_to 'Show', test_result %></td>
        <td><%= link_to 'Edit', edit_test_result_path(test_result) %></td>
        <td><%= link_to 'Destroy', test_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test result', new_test_result_path %>

app/views/test_results/new.html.erb
<h1>New test_result</h1>

<%= render 'form' %>

<%= link_to 'Back', test_results_path %>

app/views/test_results/score.html.erb
<h2><%= "#{@student.last_name}, #{@student.first_name}" -%></h2>

<p>
<h2><%= @problem_list.shift -%></h2>
<% @problem_list.shift %>
<% n = @problem_list.shift.to_i %>
<p>
	<%= Time.now.strftime("%H:%M %m/%d/%Y") -%>
<table >
  <tr>
    <th></th><th>Student </th><th>Key</th><th>Reference</th>
  </tr>
<% i = 0 %>  
<% @problem_list.each do |q| %>
	<% code = q[q.length-1,1] %>
	<% p = q.chop.chop %>
	
	<% if code == "m" %>
		<% i += 1 %>
	  <tr>
	    <td><%= i %>.</td><td><%= @user_answers[i-1] %></td><td><%= @key[i-1] %></td><td><%= p.split("/")[2] -%></td>
	  </tr>
	<% elsif code == "f" %>
		<% i += 1 %>
		<td><%= i -%>.</td><td><%= @user_answers[i-1] -%></td><td><%= @key[i-1] -%></td><td><%= p.split("?")[1].split("&")[0].split("=")[1].gsub("%20"," ") -%></td>
	<% end %>
<% end %>
</table>

<h3>Score <%= (@score*10000).round/100.0 -%>%</h3>
<p>
<% i = 0 %>
<h3>Missed Questions</h3>

<TABLE >
<% @missed_questions.each do |q| %>
	<% i += 1 %>
	<% if (i % 2 == 1) %>
	<TR>
	<% end -%>
	<td valign=top>
	<% code = q[q.length-1,1] %>
	<% p = q.chop.chop %>
	<% parray = p.split("<*>") %>
	<% if code == "m" %>
		<% problem_name = p.split("/")[2] -%>
	<% elsif code == "f" %>
		<% problem_name = URI.decode(parray[3].split("?")[1].split("&")[0].split("=")[1]) -%>
	<% end -%>
	<TABLE >
		<tr>
			<td>
				<h4><%= "#{parray[0]}. Student  #{parray[1]} Key #{parray[2]} #{problem_name}" -%></h4>
			</td>
		</tr>
		<tr>
			<TD style="width: 512px; vertical-align: top; text-align: left;" width=512>
				<IMG align=top src="http://s3.amazonaws.com/LaneCCMath/<%= parray[3] %>" BORDER=1>
			</TD>
		</tr>
	</table>
	</td>
	<% if (i % 2 == 0) %>
	</TR>
	<% end -%>
<% end -%>
</TABLE>

app/views/test_results/show.html.erb
<p id="notice"><%= notice %></p>

<% for column in TestResult.content_columns %>
<p>
  <b><%= column.human_name %>:</b> <%=h @test_result.send(column.name) %>
</p>
<% end %>

<%= link_to 'Edit', edit_test_result_path(@test_result) %> |
<%= link_to 'Back', test_results_path %>

app/views/test_results/show_test.html.erb
<SCRIPT LANGUAGE="JavaScript"><!--
function kH(e) {
var pK = e ? e.which : window.event.keyCode;
return (pK != 13)&&(pK != 3);}
document.onkeypress = kH;
if (document.layers) document.captureEvents(Event.KEYPRESS);
 --> </SCRIPT>
<SCRIPT LANGUAGE="JavaScript">
function checkNumeric(objName,questionnum) {
	// only allow 0-9 and period and minus
	var checkOK = "-.0123456789";
	var checkStr = objName;
	var allValid = true;

	for (i = 0;  i < checkStr.value.length;  i++) {
		ch = checkStr.value.charAt(i);
		for (j = 0;  j < checkOK.length;  j++)
			if (ch == checkOK.charAt(j)) break;
		if (j == checkOK.length) {
			allValid = false;
			break;
		}
	}
	if (! allValid) {
		thetext = "Only numbers are allowed in the answer to question " + questionnum + ".";
		thetext = thetext + " No other characters are allowed.";
		alert(thetext);
		return (false);
	} else 	return (true);
}

var isNS4 = (navigator.appName=="Netscape")?1:0;

function addAnswer(i, theAnswer) {
		var theURL = "<%= url_for(:controller => 'admin', :action => 'update_answers') %>" + '?answer='+i+". "+theAnswer
//		alert(theURL);
		var theParam = i+". "+theAnswer;
//		new Ajax.Request(theURL, {asynchronous:true, evalScripts:true});
		$.ajax({ url: '/admin/update_answers', data: {answer: theParam } });	}
 --> </script>

<h2><%= "#{@student.last_name}, #{@student.first_name}" -%></h2>
<%=@time.strftime("%Y-%m-%d %H:%M:%S") %>
<p>
<%= form_tag("score_try", method: "post") do %>

<h1><%= @test_list.shift %></h1>
<% if not @test_list[0].blank? %>
	<hr>
	<h3><%= @test_list[0] %></h3>
<% end -%>
<% @test_list.shift %>
<% n = @test_list.shift.to_i %>

<% choices = [] %>
<% l = "A" %>
<% 26.times do %>
	<% choices << l %>
	<% l = l.succ %>
<% end -%>

<% i = 0 %>
<% @test_list.each do |q| %>
	<% answer = @answers.items[i] %>
	<% code = q[q.length-1,1] %>
	<% p = q.chop.chop %>
	<% if code == "i" %>
		<% if not p.blank? %>
			<hr>
			<%= p %>
		<% end %>
	<% elsif code == "m" %>
		<hr>
		<A name="<%= i+1 %>"></A>
		<TABLE BORDER=0 CELLPADDING=10>
		<TR>
			<TD height=50 style="width: 50px; vertical-align: top; text-align: right;">
				<h3><%= i+=1 -%>.</h3>
			<p>
				<TABLE BORDER=1>
					<% key = p.split("/") %>
					<% k = key[key.length-1].gsub(",","").length  # only works for 9 or fewer choices double digits count as two choices.%>
					<% "A".upto(choices[k-5]) do |x| %>
						<% if answer.length <= 2 or answer.split(" ")[1] != x %>
							<%= render(:partial => "choice", :locals => {:i => i, :choice => x}) -%>
						<% else %>
							<%= render(:partial => "choice_selected", :locals => {:i => i, :choice => x}) -%>
						<% end %>
					<% end %>
				</TABLE>
			</TD>
			<TD style="width: 512px; vertical-align: top; text-align: left;" width=512 rowspan=8>
				<IMG align=top src="http://s3.amazonaws.com/LaneCCMath/<%= URI.encode(p) %>" BORDER=0>
			</TD>
		</TR>
		</TABLE>
	<% elsif code == "f" %>
		<hr>
		<A name="<%= i+1 %>"></A>
		<TABLE BORDER=0 CELLPADDING=10>
			<TR>
				<TD height=50 style="width: 50px; vertical-align: top; text-align: right;">
					<h3><%= i+=1 -%>.</h3>
				</td>
				<TD style="width: 512px; vertical-align: top; text-align: left;" width=512>
					<IMG align=top src="http://s3.amazonaws.com/LaneCCMath/<%= URI.encode(p) %>" BORDER=0>
				</TD>
			</tr>
			<tr>
				<td></td>
				<% if answer.length <= 2 %>
					<% entry = "replace this text with your answer (only numbers allowed)" -%>
				<% else %>
					<% entry = answer.split(" ") -%>
					<% entry.delete_at(0).to_s -%>
				<% end %>
				<td><input name="<%= i %>" type="text" onKeypress="if(!isNS4){if (event.keyCode > 11 && event.keyCode < 14) event.returnValue = false;}else{if (event.which > 11 && event.which < 14) return false;}" onBlur="checkNumeric(this,<%= i %>)" onChange="addAnswer(<%= i %>,this.value)" value=<%="'#{entry}'"%> size="45">
				</TD>
			</TR>
		</TABLE>
	<% end %>
	<p>
<% end -%>

<% end %>