config/routes.rb
Rails.application.routes.draw do

  get 'sessionsgem/install'

  get 'sessionsgem/bcrypt'

  
  root "welcome#index"
  
  match "test_templates/upload" => "test_templates#upload", via: [:get, :post]
  match "test_templates/save" => "test_templates#save", via: [:get, :post]
  match "students/get_test" => "students#get_test", via: [:get, :post]
  match "students/choose_student" => "students#choose_student", via: [:get, :post]
  match "students/show_record" => "students#show_record", via: [:get, :post]
  get "students/authorize" => "students#authorize"
  post "students/authorize_test" => "students#authorize_test"
  match "students/authorize_reentry" => "students#authorize_reentry", via: [:get, :post]
  post "students/authorize_reentry_test" => "students#authorize_reentry_test"
  get "test_templates/" => "test_templates#index"
  get "test_templates/show_test" => "test_templates#show_test"
  get "test_templates/destroy" => "test_templates#destroy"
  get "users/add" => "users#add"
  get "test_taker/show_test" => "test_taker#show_test"
  get "test_results/show_test" => "test_results#show_test"
  match "test_results/score" => "test_results#score", via: [:get, :post]
  match "courses/remove_student" => "courses#remove_student", via: [:get, :post]
  
  delete "users/:id" => "users#destroy"
  delete "users" => "users#destroy"
  
  resources :users, :instructors, :courses, :answer_records, :test_results, :test_templates, :students
  
  match "/login" => "admin#login", via: [:get, :post]
  match "/admin" => "admin#login", via: [:get, :post]
  match "answer/analyze_test" => "answer#analyze_test", via: [:get, :post]
  match "answer/analyze_problem" => "answer#analyze_problem", via: [:get, :post]
  match "admin/choose_student" => "students#choose_student", via: [:get, :post]
  get "admin/index" => "admin#index"
  get "admin/try-test" => "admin#try_test"
  match "admin/try_test" => "admin#try_test", via: [:get, :post]
  get "admin/authorize" => "admin#authorize"
  match "admin/authorize_class" => "admin#authorize_class", via: [:get, :post]
  match "admin/authorize_class_test" => "admin#authorize_class_test", via: [:get, :post]
  get "admin/authorize_class_test" => "admin#authorize_class_test"
  match "admin/add_student_to_course" => "admin#add_student_to_course", via: [:get, :post]
  get "admin/get_student_record" => "admin#get_student_record"
  get "admin/authorize_reentry" => "admin#authorize_reentry"
  get "admin/logout" => "admin#logout"
  match "admin/login" => "admin#login", via: [:get, :post]
  get "admin/list_users" => "admin#list_users"
  get "admin/destroy_user" => "admin#destroy_user"
  get "admin/new_user" => "admin#new_user"
  get "admin/edit_user" => "admin#edit_user"
  get "admin/add_user" => "admin#add_user"
  get "admin/add_course" => "admin#add_course"
  match "admin/add_test_to_course" => "admin#add_test_to_course", via: [:get, :post]
  get "admin/show_test_try" => "admin#show_test_try"
  get "admin/test_results" => "admin#test_results"
  match "admin/show_test_results" => "admin#show_test_results", via: :post
  match "admin/score_try" => "admin#score_try", via: [:get, :post]
  match "admin/update_answers" => "admin#update_answers", via: [:get, :post]
  match "admin/add_students" => "admin#add_students", via: [:get, :post]
  match "admin/show_class" => "admin#show_class", via: [:get, :post]
  match "test_taker/update_answers" => "test_taker#update_answers", via: [:get, :post]
  get "answer/analyze_answers" => "answer#analyze_answers"
  get "instructor/create" => "instructor#create"

end

app/models/instructor.rb
# == Schema Information
# Schema version: 11
#
# Table name: instructors
#
#  id         :integer(11)   not null, primary key
#  first_name :string(255)   
#  last_name  :string(255)   
#

class Instructor < ActiveRecord::Base

  has_many  :courses
  has_many  :test_templates

  validates_presence_of   :first_name, :last_name
  validates_uniqueness_of :first_name, :scope => 'last_name'
  
  def whole_name
    last_name+", "+first_name 
  end

  def add_course(course)
    #note: courses should be unique, no duplicates, enforced in add_course
    courses << course
  end
  
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  layout "admin"

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  def show
    @instructor = Instructor.find(params[:id])
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
    @instructor = Instructor.find(params[:id])
  end

  # POST /instructors
  def create
    @instructor = Instructor.new(instructor_params)

      if @instructor.save
        redirect_to @instructor, notice: 'Instructor was successfully added.' 
      else
        render :new 
      end
   end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
      if @instructor.update(instructor_params)
        redirect_to @instructor, notice: 'Instructor was successfully updated.' 
      else
        render :edit 
      end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
      redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' 
   end

 def add_students #adding students to a class from a spreadsheet
   @instructor = session[:instructor] #actually instructor id
   @classes = session[:courses] #instructor classes
   @n = session[:n]
   if request.post? 
     @course = Course.find(params[:course])
     @students = []
     @students_already_enrolled = []
     @students_errors = []
     student_data = params["student_data"].gsub("\r","").split("\n")
     for s in student_data do
       t = s.split("\t")
       @student = Student.new
       @student.student_number = t[0]
       @student.last_name = t[1]
       @student.first_name = t[2]
       if not @student.student_number.blank?
         @old_student = Student.find_by_student_number(@student.student_number)
         if @old_student and @old_student.first_name == @student.first_name and @old_student.last_name == @student.last_name
           if @course.students.detect {|s| s == @old_student}
#                flash[:notice] = "#{@student.first_name} #{@student.last_name} is already enrolled in #{@course.course_name}"
             @students_already_enrolled << @student
           else
             @student.add_course(@course)
#                flash[:notice] += "Old student #{@student.first_name} #{@student.last_name} successfully enrolled in #{@course.course_name}"
             @students  << @student
           end
         elsif @student.save
            @student.add_course(@course)
            flash[:notice] += "New student #{@student.first_name} #{@student.last_name} successfully enrolled in #{@course.course_name}"
            @students  << @student
          else
            @students_errors  << @student
          end
       else
         @students_errors  << @student
#            flash[:notice] = "Error, student number is blank. #{@student.first_name} #{@student.last_name}"
       end
     end
   end
 end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:first_name, :last_name)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<div class="user-form">
<%= form_for(@instructor) do |f| %>
  <% if @instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% @instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<fieldset>
		<legend>Enter Instructor Data</legend>
		<p><label for="instructor_first_name">First name</label>
		<%= text_field 'instructor', 'first_name'  %></p>

		<p><label for="instructor_last_name">Last name</label>
		<%= text_field 'instructor', 'last_name'  %></p>

	    <%= f.submit %>
	</fieldset>
  </div>
<% end %>
<p/>

app/views/instructors/edit.html.erb
<h1>Editing instructor</h1>

<%= render 'form' %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<h1>Listing instructors</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.first_name %></td>
        <td><%= instructor.last_name %></td>
        <td><%= instructor.id %></td>
		<td>
			<% courses = Course.where("instructor_id = ?",instructor.id ) %>
			<%= select_tag :courses, options_from_collection_for_select(courses, :id, :course_name, selected_value = nil)%>
		</td>
        <td><%= link_to 'Show', instructor %></td>
        <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
        <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/instructors/new.html.erb
<h1>New instructor</h1>

<%= render 'form' %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<% for column in Instructor.content_columns %>
<p>
  <b><%= column.human_name %>:</b> <%=h @instructor.send(column.name) %>
</p>
<% end %>

<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>